### ISSUE TITLE
TypeError: Nonetype

### ISSUE THREAD

**Issue by fmilante** [HenrYxZ/object-classification#4]
Traceback (most recent call last):
  File "C:\Users\Sacelle\Desktop\object-classification-master\main.py", line 102, in <module>
    main()
  File "C:\Users\Sacelle\Desktop\object-classification-master\main.py", line 63, in main
    codebook = utils.load(codebook_filename)
  File "C:\Users\Sacelle\Desktop\object-classification-master\utils.py", line 116, in load
    data = sio.loadmat(filename)
  File "C:\Python36\lib\site-packages\scipy\io\matlab\mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "C:\Python36\lib\site-packages\scipy\io\matlab\mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
**TypeError: 'NoneType' object is not iterable**

**Comment by HenrYxZ** [comment]
That may be because you are trying to load a codebook when you don't have any in your project, so to avoid that, when you are prompt "Enter [1] for generating a new codebook or [2] to load one" enter 1 and generate a new one
